spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
pfcc:
  jobs:
    drop-outdated-security-tokens:
      outdated-security-token-ttl: 10d
      enabled: true
      cron: '0 0 0 * * *'
  mail:
    do-not-reply-address: 'dont-reply@pfcalc.org.ua'
  auth:
    key-algorithm: RSA
    auth-token-expiration: 10m
    refresh-token-expiration: 10d
    same-site: lax
