spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
pfcc:
  mail:
    do-not-reply-address: 'dont-reply@pfcalc.org.ua'
  jwt:
    key-algorithm: RSA
    expiration: 20m
