name: Deploy to AWS
on:
  workflow_dispatch:
  release:
    types:
      - released
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          path: target/pfcc-*.jar
