name: Deploy to AWS
on:
  workflow_dispatch:
  push:
    branches:
      - configure_continuous_delivery
  release:
    types:
      - released
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Deploy to AWS
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" | tr -d '\r' > key.pem
          chmod 400 key.pem
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan 3.78.190.177 >> ~/.ssh/known_hosts
          scp -i key.pem target/pfcc-*.jar ec2-user@3.78.190.177:/home/ec2-user/pfcc.jar
          ssh -i key.pem ec2-user@3.78.190.177 fuser -k 8080/tcp
          ssh -i key.pem ec2-user@3.78.190.177 java -jar pfcc.jar
